esphome:
  name: smart_feeder
  platform: ESP8266
  board: nodemcuv2
  includes:
    - crowtail_weight_sensor.h

globals:
  - id: target_weight # in grams
    type: int
    restore_value: yes
    initial_value: '30'
  - id: feeder_interval # in hours
    type: int
    restore_value: yes
    initial_value: '5'
  - id: performed_rotations
    type: int
    initial_value: '0'
  - id: is_feeder_broken
    type: bool
    initial_value: 'false'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:

script:
 - id: feed
   then:
      - while:
          condition:
            - lambda: |-
                return id(performed_rotations) < 10;
            - lambda: |-
                return id(crowtail_weight_sensor).state <= id(target_weight);
          then:
            - logger.log: "Triggered"
            - servo.write:
                id: pet_feeder
                level: -100.0%
            - delay: 2s
            - servo.write:
                id: pet_feeder
                level: 100.0%
            - delay: 2s
            - lambda: id(performed_rotations) += 1;
      - lambda: |-
          if(id(performed_rotations) >= 10) {
            id(is_feeder_broken) = true;
          } else {
            id(is_feeder_broken) = false;
          }
          id(performed_rotations) = 0;

api:
  reboot_timeout: 0s
  services:
    # Update weight and time period of the feeder
    - service: change_target_weight
      variables:
        new_target_weight: int
      then:
        - lambda: |-
            id(target_weight) = new_target_weight;
    - service: change_feed_interval
      variables:
        new_feed_interval: int
      then:
        - lambda: |-
            id(feeder_interval) = new_feed_interval;
    # Manual feeder trigger through HA
    - service: refill_food
      then:
        - script.execute: feed

sensor:
  # Custom weight sensor
  - platform: custom
    lambda: |-
      auto weight_sensor = new CrowtailWeightSensor();
      App.register_component(weight_sensor);
      return {weight_sensor};
    sensors:
      name: "Weight Sensor"
      id: crowtail_weight_sensor
      unit_of_measurement: gram
  # Template sensors to communicate values to HA
  - platform: template
    name: "Hours since last feed"
    update_interval: 5min
    id: hours_since_last_feed
    lambda: |- # Rounding float seconds to the nearest int hour
      int roundToHour = id(uptime_sensor).state/3600 + 0.5;
      return roundToHour % id(feeder_interval);
  - platform: template
    name: "Pet feeder interval"
    update_interval: 5min
    lambda: |-
      return id(feeder_interval);
  - platform: template
    name: "Pet feeder target weight"
    lambda: |-
      return id(target_weight);  
  - platform: template
    update_interval: 10min
    name: "Is feeder broken"
    id: is_feeder_broken_sensor
    lambda: |-
      return id(is_feeder_broken);
  # Uptime sensor to execute feeder on fixed time interval
  - platform: uptime
    id: uptime_sensor
    update_interval: 60min
    on_value:
      then:
      - if:
          condition:
            - lambda: |- # Rounding float seconds to the nearest int hour
                int roundToHour = id(uptime_sensor).state/3600 + 0.5;
                return (roundToHour % id(feeder_interval)) == 0;
          then:
            - script.execute: feed

servo:
  - id: pet_feeder
    output: pwm_output

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D5
    frequency: 50 Hz
